import { readFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import type { Tenant } from '@ragstone/shared';
import { auditTenantContrast, parseTenant } from './tenantDocument';
import { TENANTS, acme, meridian } from './tenants';

describe('parseTenant', () => {
  it('takes a complete, valid document as written', () => {
    const { tenant, issues } = parseTenant(JSON.parse(JSON.stringify(meridian)), acme);
    expect(tenant).toEqual(meridian);
    expect(issues).toEqual([]);
  });

  describe('repairs rather than rejects', () => {
    it('falls back on a malformed colour and says which field', () => {
      const { tenant, issues } = parseTenant({ palette: { primary: 'not-a-colour' } }, acme);

      expect(tenant.palette.primary).toBe(acme.palette.primary);
      expect(issues).toContainEqual(
        expect.objectContaining({ path: 'palette.primary', level: 'repaired' }),
      );
    });

    it('falls back on a number outside its range', () => {
      const { tenant, issues } = parseTenant({ density: { spacing: 400 } }, acme);

      expect(tenant.density.spacing).toBe(acme.density.spacing);
      expect(issues).toContainEqual(
        expect.objectContaining({ path: 'density.spacing', message: expect.stringMatching(/2–24/) }),
      );
    });

    it('falls back on the wrong type without discarding the rest of the document', () => {
      const { tenant } = parseTenant(
        { brand: { name: 42, initials: 'XX' }, shape: { radius: 4 } },
        acme,
      );

      expect(tenant.brand.name).toBe(acme.brand.name);
      expect(tenant.brand.initials).toBe('XX');
      expect(tenant.shape.radius).toBe(4);
    });

    it('rejects an unknown button transform but keeps everything else', () => {
      const { tenant, issues } = parseTenant(
        { typography: { buttonTextTransform: 'sideways', headingWeight: 800 } },
        acme,
      );

      expect(tenant.typography.buttonTextTransform).toBe(acme.typography.buttonTextTransform);
      expect(tenant.typography.headingWeight).toBe(800);
      expect(issues).toContainEqual(
        expect.objectContaining({ path: 'typography.buttonTextTransform' }),
      );
    });

    it('accepts node colours for types it has never heard of', () => {
      // A domain pack may declare entities this build does not know about.
      const { tenant, issues } = parseTenant(
        { graph: { nodeColors: { Molecule: '#123456', Broken: 'nope' } } },
        acme,
      );

      expect(tenant.graph.nodeColors['Molecule']).toBe('#123456');
      expect(tenant.graph.nodeColors['Broken']).toBeUndefined();
      expect(issues).toContainEqual(
        expect.objectContaining({ path: 'graph.nodeColors.Broken' }),
      );
    });

    it('ignores empty starter lists rather than showing none', () => {
      const { tenant } = parseTenant({ copy: { starters: [] } }, acme);
      expect(tenant.copy.starters).toEqual(acme.copy.starters);
    });
  });

  describe('contrast is reported, not silently corrected', () => {
    it('warns when a brand colour cannot carry readable text', () => {
      // #7A7A7A sits in the narrow band where neither candidate clears AA:
      // white reaches 4.29:1 and the dark ink 4.40:1, both under 4.5. Most
      // mid-greys do pass — #767676 clears it at 4.54:1 with white — so the
      // fixture has to be chosen deliberately rather than guessed.
      const { issues } = parseTenant({ palette: { primary: '#7A7A7A' } }, acme);

      expect(issues).toContainEqual(
        expect.objectContaining({ level: 'warning', path: 'palette.primary' }),
      );
    });

    it('leaves the client colour intact — altering their brand is worse', () => {
      const { tenant } = parseTenant({ palette: { primary: '#7A7A7A' } }, acme);
      expect(tenant.palette.primary).toBe('#7A7A7A');
    });

    it('warns when a node colour disappears into the canvas', () => {
      const nearlyInvisible: Tenant = {
        ...acme,
        graph: { ...acme.graph, nodeColors: { Ghost: '#F5F7F9' }, background: '#FFFFFF' },
      };

      expect(auditTenantContrast(nearlyInvisible)).toContainEqual(
        expect.objectContaining({ path: 'graph.nodeColors.Ghost' }),
      );
    });
  });
});

describe('the served documents', () => {
  // Generated by scripts/emit-tenants.mjs. This is what stops the bundled
  // fallback and the fetched document drifting apart unnoticed.
  const dir = join(__dirname, '..', '..', 'public', 'tenants');
  const documents = readdirSync(dir)
    .filter((file) => file.endsWith('.json'))
    .map((file) => [file, JSON.parse(readFileSync(join(dir, file), 'utf8'))] as const);

  it('exist for every bundled tenant', () => {
    expect(documents.map(([file]) => file).sort()).toEqual(
      Object.keys(TENANTS)
        .map((id) => `${id}.json`)
        .sort(),
    );
  });

  it.each(documents)('%s parses with no repairs and no warnings', (_file, document) => {
    const { issues } = parseTenant(document, acme);
    expect(issues).toEqual([]);
  });

  it.each(documents)('%s matches the bundled tenant exactly', (_file, document) => {
    const { tenant } = parseTenant(document, acme);
    expect(tenant).toEqual(TENANTS[tenant.id]);
  });
});

describe('a tenant on another subject', () => {
  /**
   * A domain declares which types exist; a tenant declares how they look. The
   * merge has to respect that: inheriting the base tenant's colours across a
   * domain boundary leaves a clinical console holding a colour for Supplier —
   * a type its graph cannot contain, offered by a palette with no business
   * declaring it. Downstream, that colour map was also the type registry, so
   * the console would have offered Supplier as something to filter by.
   */
  it('reads the domain a document declares', () => {
    const { tenant } = parseTenant({ domain: 'clinical-trials' }, acme);

    expect(tenant.domain).toBe('clinical-trials');
  });

  it('does not inherit colours for types it cannot hold', () => {
    const { tenant } = parseTenant(
      { domain: 'clinical-trials', graph: { nodeColors: { Trial: '#123456' } } },
      acme,
    );

    expect(Object.keys(tenant.graph.nodeColors)).toEqual(['Trial']);
    expect(tenant.graph.nodeColors.Supplier).toBeUndefined();
  });

  it('still inherits colours within the same subject', () => {
    // The repair that made partial documents workable is unchanged where it
    // still makes sense: same types, so the base's colours apply.
    const { tenant } = parseTenant(
      { graph: { nodeColors: { Supplier: '#123456' } } },
      acme,
    );

    expect(tenant.graph.nodeColors.Supplier).toBe('#123456');
    expect(tenant.graph.nodeColors.Risk).toBe(acme.graph.nodeColors.Risk);
  });

  it('treats a document with no domain as the base tenant’s subject', () => {
    const { tenant } = parseTenant({}, acme);

    expect(tenant.domain).toBe(acme.domain);
    expect(tenant.graph.nodeColors).toEqual(acme.graph.nodeColors);
  });
});
